---
# Sample test case for ha- stop nova service and remove configure files

schema: "yardstick:task:0.1"

scenarios:
-
  type: ServiceHA
  options:
    attackers:
    - fault_type: "stopRemove-configfile"
      process_name: "nova-api"
      conf_name: "/etc/nova/nova.conf"
      host: node1
    monitors:
    - monitor_cmd: "nova image-list"
      monitor_time: 10
  nodes:
    node1: node1.LF
  runner:
    type: Duration
    duration: 1
  sla:
    outage_time: 5
    action: monitor

context:
  type: Node
  name: LF
  file: /etc/haverifier/pod.yaml


