---
# Sample test case for ha- stop keystone service and remove configure files

schema: "yardstick:task:0.1"

scenarios:
-
  type: ServiceHA
  options:
    attackers:
    - fault_type: "stopRemove-configfile"
      process_name: "keystone"
      conf_name: "/etc/keystone/keystone.conf"
      host: node1
    monitors:
    - monitor_type: "openstack-cmd"
      command_name: "keystone user-list"
      monitor_time: 10
      sla:
        max_outage_time: 5
  nodes:
    node1: node1.LF
  runner:
    type: Duration
    duration: 1
  sla:
    outage_time: 5
    action: monitor

context:
  type: Node
  name: LF
  file: /etc/haverifier/pod.yaml


